export const liveGames = [
  {
    id: 1,
    homeTeam: "Lakers",
    awayTeam: "Warriors",
    homeScore: 98,
    awayScore: 102,
    quarter: "4th",
    timeLeft: "2:34",
    isLive: true,
    viewers: 45200,
    thumbnail: "/lakers-warriors-live.jpg",
  },
  {
    id: 2,
    homeTeam: "Celtics",
    awayTeam: "Heat",
    homeScore: 87,
    awayScore: 91,
    quarter: "3rd",
    timeLeft: "8:15",
    isLive: true,
    viewers: 32800,
    thumbnail: "/celtics-heat-live.jpg",
  },
  {
    id: 3,
    homeTeam: "Cowboys",
    awayTeam: "Giants",
    homeScore: 21,
    awayScore: 14,
    quarter: "2nd",
    timeLeft: "5:42",
    isLive: true,
    viewers: 78500,
    thumbnail: "/cowboys-giants-live.jpg",
  },
  {
    id: 4,
    homeTeam: "Chiefs",
    awayTeam: "Bills",
    homeScore: 28,
    awayScore: 24,
    quarter: "4th",
    timeLeft: "1:58",
    isLive: true,
    viewers: 92300,
    thumbnail: "/chiefs-bills-live.jpg",
  },
  {
    id: 5,
    homeTeam: "Dodgers",
    awayTeam: "Yankees",
    homeScore: 7,
    awayScore: 4,
    quarter: "8th",
    timeLeft: "Bottom",
    isLive: true,
    viewers: 56700,
    thumbnail: "/dodgers-yankees-live.jpg",
  },
]

export const sportsShows = [
  {
    id: 1,
    title: "SportsCenter",
    description: "The latest sports news and highlights",
    duration: "60 min",
    isLive: true,
    thumbnail: "/sportscenter-show.jpg",
    category: "News",
  },
  {
    id: 2,
    title: "First Take",
    description: "Stephen A. Smith and debate panel discuss hot topics",
    duration: "120 min",
    isLive: false,
    thumbnail: "/first-take-show.jpg",
    category: "Talk Show",
  },
  {
    id: 3,
    title: "NFL GameDay",
    description: "Pre-game analysis and predictions",
    duration: "180 min",
    isLive: true,
    thumbnail: "/nfl-gameday-show.jpg",
    category: "Analysis",
  },
  {
    id: 4,
    title: "NBA Tonight",
    description: "Comprehensive basketball coverage",
    duration: "90 min",
    isLive: false,
    thumbnail: "/nba-tonight-show.jpg",
    category: "Analysis",
  },
  {
    id: 5,
    title: "Baseball Tonight",
    description: "MLB highlights and analysis",
    duration: "60 min",
    isLive: false,
    thumbnail: "/baseball-tonight-show.jpg",
    category: "Analysis",
  },
]

export const gameHighlights = [
  {
    id: 1,
    title: "LeBron's Monster Dunk",
    description: "King James throws down a thunderous slam",
    duration: "0:45",
    views: "2.3M",
    thumbnail: "/lebron-dunk-highlight.jpg",
    sport: "NBA",
  },
  {
    id: 2,
    title: "Mahomes 50-Yard TD Pass",
    description: "Perfect spiral finds Kelce in the endzone",
    duration: "1:12",
    views: "1.8M",
    thumbnail: "/mahomes-td-highlight.jpg",
    sport: "NFL",
  },
  {
    id: 3,
    title: "Judge's 500th Home Run",
    description: "Historic milestone reached in dramatic fashion",
    duration: "2:30",
    views: "3.1M",
    thumbnail: "/judge-homerun-highlight.jpg",
    sport: "MLB",
  },
  {
    id: 4,
    title: "Curry's Deep Three",
    description: "Logo shot from way downtown",
    duration: "0:38",
    views: "4.2M",
    thumbnail: "/curry-three-highlight.jpg",
    sport: "NBA",
  },
  {
    id: 5,
    title: "Messi's Free Kick Goal",
    description: "Incredible curve beats the keeper",
    duration: "1:05",
    views: "5.7M",
    thumbnail: "/messi-freekick-highlight.jpg",
    sport: "Soccer",
  },
  {
    id: 6,
    title: "Ohtani's Two-Way Performance",
    description: "Pitches 7 innings, hits 2 home runs",
    duration: "3:45",
    views: "2.9M",
    thumbnail: "/ohtani-performance-highlight.jpg",
    sport: "MLB",
  },
]

export const fullGames = [
  {
    id: 1,
    title: "Lakers vs Warriors - Game 7",
    description: "Epic playoff battle goes to overtime",
    duration: "3:42:15",
    date: "2024-05-15",
    thumbnail: "/lakers-warriors-game7.jpg",
    sport: "NBA",
    featured: true,
  },
  {
    id: 2,
    title: "Super Bowl LVIII",
    description: "Chiefs defeat 49ers in thrilling finish",
    duration: "4:18:30",
    date: "2024-02-11",
    thumbnail: "/superbowl-58.jpg",
    sport: "NFL",
    featured: true,
  },
  {
    id: 3,
    title: "World Series Game 6",
    description: "Dodgers clinch championship at home",
    duration: "3:28:45",
    date: "2024-10-30",
    thumbnail: "/world-series-game6.jpg",
    sport: "MLB",
    featured: false,
  },
  {
    id: 4,
    title: "Champions League Final",
    description: "Real Madrid vs Manchester City",
    duration: "2:15:20",
    date: "2024-06-01",
    thumbnail: "/champions-league-final.jpg",
    sport: "Soccer",
    featured: false,
  },
  {
    id: 5,
    title: "NBA Finals Game 4",
    description: "Celtics even the series with dominant win",
    duration: "2:58:12",
    date: "2024-06-14",
    thumbnail: "/nba-finals-game4.jpg",
    sport: "NBA",
    featured: false,
  },
]

export const newsArticles = [
  {
    id: 1,
    title: "Trade Deadline Shakeup: Star Player Moves to Contender",
    excerpt:
      "In a blockbuster deal that shocked the league, the All-Star forward has been traded to a championship contender.",
    category: "Trade",
    timestamp: "2 hours ago",
    author: "Mike Johnson",
    thumbnail: "/trade-news.jpg",
    size: "large",
  },
  {
    id: 2,
    title: "Injury Update: Superstar Expected to Return Next Week",
    excerpt: "Medical team optimistic about quick recovery timeline.",
    category: "Injury",
    timestamp: "4 hours ago",
    author: "Sarah Williams",
    thumbnail: "/injury-update.jpg",
    size: "wide",
  },
  {
    id: 3,
    title: "Rookie of the Year Race Heating Up",
    excerpt: "Three candidates emerge as frontrunners with stellar performances.",
    category: "Awards",
    timestamp: "6 hours ago",
    author: "David Chen",
    thumbnail: "/rookie-race.jpg",
    size: "tall",
  },
  {
    id: 4,
    title: "Contract Extension Talks Begin",
    excerpt: "Franchise player and team discussing long-term deal.",
    category: "Contract",
    timestamp: "8 hours ago",
    author: "Lisa Rodriguez",
    thumbnail: "/contract-talks.jpg",
    size: "medium",
  },
  {
    id: 5,
    title: "Coach of the Year Candidates",
    excerpt: "Five coaches have transformed their teams this season.",
    category: "Coaching",
    timestamp: "12 hours ago",
    author: "Tom Anderson",
    thumbnail: "/coach-candidates.jpg",
    size: "medium",
  },
  {
    id: 6,
    title: "Draft Lottery Results Announced",
    excerpt: "Surprising outcome shakes up draft order predictions.",
    category: "Draft",
    timestamp: "1 day ago",
    author: "Jennifer Lee",
    thumbnail: "/draft-lottery.jpg",
    size: "wide",
  },
]

export const mvpCandidates = [
  {
    id: 1,
    name: "Nikola Jokić",
    team: "Nuggets",
    stats: "26.4 PPG, 12.4 RPG, 9.0 APG",
    odds: "+150",
    position: 1,
  },
  {
    id: 2,
    name: "Luka Dončić",
    team: "Mavericks",
    stats: "32.4 PPG, 8.6 RPG, 9.1 APG",
    odds: "+200",
    position: 2,
  },
  {
    id: 3,
    name: "Shai Gilgeous-Alexander",
    team: "Thunder",
    stats: "30.3 PPG, 5.5 RPG, 6.2 APG",
    odds: "+300",
    position: 3,
  },
  {
    id: 4,
    name: "Jayson Tatum",
    team: "Celtics",
    stats: "26.9 PPG, 8.1 RPG, 4.9 APG",
    odds: "+500",
    position: 4,
  },
]

export const standings = [
  { team: "Celtics", wins: 48, losses: 12, pct: ".800" },
  { team: "Nuggets", wins: 44, losses: 16, pct: ".733" },
  { team: "Thunder", wins: 43, losses: 17, pct: ".717" },
  { team: "Mavericks", wins: 41, losses: 19, pct: ".683" },
  { team: "Lakers", wins: 38, losses: 22, pct: ".633" },
]

export const breakingNews = [
  "🚨 BREAKING: Star quarterback signs record-breaking contract extension",
  "⚡ LIVE: Championship game goes to overtime - 45M viewers watching",
  "🏆 JUST IN: MVP award winner announced after historic season",
  "📈 TRENDING: Rookie breaks 50-year-old scoring record",
  "🔥 UPDATE: Trade deadline deal sends shockwaves through league",
]
